SELECT * FROM EMP; --CONSULTA 1
SELECT * FROM DEPT; --CONSULTA 2
SELECT * FROM EMP WHERE JOB LIKE 'CLERK'; --CONSULTA 3
SELECT * FROM EMP WHERE JOB LIKE 'CLERK' ORDER BY ENAME ASC;--CONSULTA 4
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO FROM EMP WHERE JOB IN('CLERK') ORDER BY ENAME ASC;--CONSULTA 5
SELECT EMPNO,ENAME,SAL FROM EMP; --CONSULTA 6
SELECT DNAME FROM DEPT; --CONSULTA7
SELECT DNAME FROM DEPT ORDER BY DNAME ASC; --CONSULTA8
SELECT DNAME FROM DEPT ORDER BY LOC ASC; --CONSULTA9
SELECT DNAME FROM DEPT ORDER BY DNAME DESC; --CONSULTA10
SELECT ENAME,JOB FROM EMP ORDER BY SAL ASC; --CONSULTA11
SELECT ENAME,JOB FROM EMP ORDER BY JOB ASC, SAL ASC; --CONSULTA12
SELECT ENAME,JOB FROM EMP ORDER BY JOB DESC, SAL ASC; --CONSULTA13
SELECT DEPTNO,COMM FROM EMP WHERE DEPTNO LIKE 30; --CONSULTA14
SELECT DEPTNO,COMM FROM EMP WHERE DEPTNO LIKE 30 ORDER BY COMM ASC; --CONSULTA15
SELECT COMM FROM EMP; --CONSULTA16A
SELECT DISTINCT COMM FROM EMP; --CONSULTA16B
SELECT DISTINCT ENAME,COMM FROM EMP; --CONSULTA17 XXXX
SELECT DISTINCT ENAME,SAL FROM EMP; --CONSUTLA18 XXXX
SELECT DISTINCT COMM,EMPNO FROM EMP; --CONSULTA19
SELECT ENAME,SAL+1000 AS "SALARIO EXTRA" FROM EMP WHERE DEPTNO LIKE 30; --CONSULTA20
SELECT ENAME,SAL,SAL+1000 AS "NUEVO SALARIO" FROM EMP WHERE DEPTNO LIKE 30; --CONSULTA21
SELECT ENAME FROM EMP WHERE COMM >= SAL/2; --CONSULTA22
SELECT ENAME FROM EMP WHERE COMM <= SAL*0.25; --CONSULTA23
SELECT 'NOMBRE:'||' '||ENAME AS NOMBRE,'SALARIO:'||' '||SAL AS SALARIO FROM EMP; --CONSULTA24
SELECT EMPNO,SAL,COMM FROM EMP WHERE EMPNO > 7500; --CONSULTA25
SELECT * FROM EMP WHERE ENAME >= 'J' ORDER BY ENAME ASC; --CONSULTA26
SELECT SAL,COMM,SAL+COMM AS "SAL + COMM" FROM EMP WHERE COMM IS NOT NULL ORDER BY EMPNO ASC; --CONSULTA27
SELECT SAL,COMM,SAL+COMM AS "SAL + COMM" FROM EMP WHERE COMM IS NULL ORDER BY EMPNO ASC; --CONSULTA28
SELECT ENAME FROM EMP WHERE SAL > 1000 AND MGR = 7698; --CONSULTA29
SELECT ENAME FROM EMP WHERE SAL > 1000 AND MGR != 7698; --CONSULTA30
SELECT ENAME,NVL((COMM*100/SAL),0) AS PORCENTAJE FROM EMP; --CONSULTA31
SELECT ENAME,DEPTNO FROM EMP WHERE DEPTNO = 10 AND ENAME NOT LIKE '%LA%'; --CONSULTA32
SELECT ENAME FROM EMP WHERE MGR IS NULL; --CONSULTA33
SELECT DNAME FROM DEPT WHERE DEPTNO NOT IN (20,30); --CONSULTA34
SELECT ENAME, DEPTNO FROM EMP WHERE JOB = 'CLERK' AND DEPTNO <> 10 AND SAL > 800 ORDER BY HIREDATE ASC; --CONSULTA35
SELECT ENAME,ROUND(SAL/COMM,2) AS COCIENTE FROM EMP WHERE COMM IS NOT NULL AND COMM <> 0 ORDER BY ENAME ASC; --CONSULTA36
SELECT * FROM EMP WHERE ENAME LIKE '_____'; --CONSULTA37
SELECT * FROM EMP WHERE ENAME LIKE '_____%'; --CONSULTA38
SELECT * FROM EMP WHERE ENAME LIKE 'A%' AND SAL > 1000 OR COMM NOT IN NULL AND DEPTNO = 30; --CONSULTA39
SELECT ENAME , SAL , NVL((SAL-COMM),SAL) AS "SUELDO TOTAL"  FROM EMP ORDER BY SAL DESC, "SUELDO TOTAL" DESC; --CONSULTA40
SELECT ENAME, SAL, COMM FROM  EMP WHERE SAL > (COMM)/2 AND SAL < COMM; --CONSULTA41
SELECT ENAME, SAL, NVL(COMM,0) FROM  EMP WHERE SAL < NVL((COMM),0)/2 OR SAL > NVL(COMM,0); --CONSULTA42
SELECT ENAME, JOB  FROM  EMP WHERE ENAME LIKE 'A%' AND JOB LIKE '%MAN'; --CONSULTA43
SELECT ENAME, JOB  FROM  EMP WHERE ENAME LIKE 'A____' JOIN SELECT job FROM emp where job LIKE '%MAN'; --CONSULTA44
SELECT ENAME, JOB FROM EMP WHERE ENAME || JOB LIKE 'A%MAN'; --CONSULTA45
SELECT ENAME, SAL, (SAL*1.06-NVL(COMM,0)) AS "6%", (SAL*1.06*1.07-NVL(COMM,0)) AS "7%", CASE WHEN COMM IS NULL OR COMM = 0 THEN 'NO' ELSE 'SI' END AS "TIENE COMISION" FROM EMP; --CONSULTA46
SELECT ENAME, HIREDATE FROM EMP WHERE JOB NOT LIKE 'SALESMAN'; --CONSULTA47
SELECT * FROM EMP WHERE EMPNO IN (7844, 7900, 7521, 7521, 7782, 7934, 7678, 7369) AND EMPNO NOT IN (7902, 7839, 7499, 7878); --CONSULTA48
SELECT * FROM EMP ORDER BY MGR ASC, EMPNO DESC; --CONSULTA49
SELECT ENAME, EMPNO, MGR, SAL, DEPTNO FROM EMP WHERE EMPNO < MGR AND SAL BETWEEN 1000 AND 2000 OR DEPTNO = 30; --CONSULTA50
SELECT MAX(SAL), SUM(SAL), COUNT(ENAME) FROM  EMP; --CONSULTA51

