CREATE TABLE ESTUDIANTE (
    NOMBRE VARCHAR2(20),
    APELLIDO VARCHAR2(30) NOT NULL,
    DOMICILIO VARCHAR2(30) UNIQUE,
    TELEFONO VARCHAR2(11),
    CONSTRAINT PK_ESTUDIANTE PRIMARY KEY (NOMBRE)
);


CREATE TABLE CONDUCTORES (
    NIF VARCHAR2(9) PRIMARY KEY,
    NOMBRE VARCHAR2(25) NOT NULL,
    APELLIDOS VARCHAR2(40) NOT NULL,
    FOTO BLOB NOT NULL,
    EDAD NUMBER(2) CHECK (EDAD BETWEEN 18 AND 99),
    TIPO_CARNET VARCHAR2(2) CHECK (TIPO_CARNET IN ('A1','A2','A','B1','B2','C','D','E')),
    FECHA_CARNET DATE DEFAULT SYSDATE,
    INTENTOS NUMBER CHECK (INTENTOS < 10)
);



CREATE TABLE VEHICULOS (
    MATRICULA VARCHAR2(10) PRIMARY KEY,
    ANTIGUEDAD NUMBER CONSTRAINT CK_ANTIGUEDAD CHECK (ANTIGUEDAD BETWEEN 1 AND 20)
);


CREATE TABLE CLIENTES (
    NIF VARCHAR2(9) PRIMARY KEY,
    NOMBRE VARCHAR2(25),
    APELLIDOS VARCHAR2(40),
    FECHA_NACIMIENTO DATE NOT NULL,
    SALARIO NUMBER CHECK (SALARIO BETWEEN 700 AND 1800),
    COTIZ NUMBER(10,2),
    HIJOS NUMBER(1) CHECK (HIJOS IN (0,1)),
    MATRICULA VARCHAR2(10),
    CONSTRAINT FK_VEHICULO_CLIENTE FOREIGN KEY (MATRICULA) REFERENCES VEHICULOS(MATRICULA) ON DELETE CASCADE
);



CREATE TABLE INGREDIENTE (
    ID NUMBER(1) PRIMARY KEY,
    NOMBRE VARCHAR2(20) UNIQUE,
    TIPO VARCHAR2(20) CHECK (TIPO IN ('HIERBA', 'CARNE', 'PESCADO', 'SAZON'))
);


CREATE TABLE RECETA (
    ID NUMBER(2) PRIMARY KEY,
    NOMBREPLATO VARCHAR2(20) NOT NULL,
    PAIS VARCHAR2(20),
    PRECIO NUMBER(3) CHECK (PRECIO BETWEEN 10 AND 150),
    ID2 NUMBER REFERENCES INGREDIENTE(ID) ON DELETE CASCADE
);



CREATE TABLE EMPLEADOS (
    DOCUMENTO CHAR(8) NOT NULL,
    NOMBRE VARCHAR2(10),
    DOMICILIO VARCHAR2(30),
    CIUDAD VARCHAR2(20) DEFAULT 'Buenos Aires'
);


ALTER TABLE EMPLEADOS ADD INFORMACION NUMBER(3);


ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY (DOCUMENTO);


ALTER TABLE EMPLEADOS ADD HIJOS NUMBER(2) CONSTRAINT CK_HIJOS CHECK (HIJOS <= 30);


ALTER TABLE EMPLEADOS ADD SUELDO NUMBER(6,2) DEFAULT 0 NOT NULL;


ALTER TABLE EMPLEADOS ADD CONSTRAINT CK_SUELDO_POS CHECK (SUELDO >= 0);


ALTER TABLE EMPLEADOS RENAME COLUMN HIJOS TO EDADEMP;


ALTER TABLE EMPLEADOS MODIFY DOMICILIO DEFAULT 'Alcala';



CREATE TABLE REVISTA (
    NUMERO_REGISTRO NUMBER PRIMARY KEY,
    TITULO VARCHAR2(50),
    PERIODICIDAD VARCHAR2(20),
    TIPO VARCHAR2(20)
);


INSERT INTO REVISTA VALUES (1, 'REVISTA A', 'SEMANAL', 'INFORMATICA');
INSERT INTO REVISTA VALUES (2, 'REVISTA B', 'SEMANAL', 'CIENCIA');
INSERT INTO REVISTA VALUES (3, 'REVISTA C', 'MENSUAL', 'MOTOR');


CREATE VIEW REVISTA_VISTA AS 
SELECT NUMERO_REGISTRO, TITULO, PERIODICIDAD FROM REVISTA;


SELECT TITULO AS NOMBRE_REVISTA, PERIODICIDAD AS FRECUENCIA 
FROM REVISTA 
WHERE NUMERO_REGISTRO > 3;



SELECT * FROM ALL_TABLES WHERE OWNER = 'ALUMNO';


DROP TABLE TAL;