-- ============================================================
-- 📝 BLOQUE 2 — Estructuras de Control: Bucles
-- ============================================================
-- Lee la teoría en: teoria/T02_bucles.md
-- Valida tus soluciones con: tests/T02_bucles.sql
-- ============================================================

SET SERVEROUTPUT ON;

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.1 — Suma del 1 al 10 con FOR
-- ────────────────────────────────────────────────────────────
-- Declara una variable "suma" inicializada a 0.
-- Usa un bucle FOR (de 1 a 10) para acumular la suma de los números.
-- Imprime el resultado con formato: "Suma del 1 al 10: 55"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.2 — Suma del 1 al 10 con WHILE
-- ────────────────────────────────────────────────────────────
-- Declara una variable "suma" inicializada a 0.
-- Declara una variable "i" inicializada a 1.
-- Usa un bucle WHILE (mientras i <= 10) para acumular la suma.
-- Imprime el resultado con formato: "Suma del 1 al 10: 55"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.3 — Mayor de tres números
-- ────────────────────────────────────────────────────────────
-- Declara tres variables numéricas (n1, n2, n3) leídas por teclado.
-- Declara una variable "mayor" para almacenar el resultado.
-- Usa IF/ELSIF/ELSE para determinar cuál es el mayor.
-- Imprime: "El mayor es: X"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.4 — Distancia entre dos puntos
-- ────────────────────────────────────────────────────────────
-- Declara variables para: x1, y1, x2, y2 (todas NUMBER, teclado).
-- Declara una variable "distancia" para almacenar el resultado.
-- Calcula la distancia euclidiana: d = SQRT((x2-x1)^2 + (y2-y1)^2)
-- Usa POWER para la potencia y SQRT para la raíz cuadrada.
-- Imprime: "Distancia entre los puntos: X"
-- (Para x1=0, y1=0, x2=3, y2=4 el resultado es 5)
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.5 — Factorial de un número
-- ────────────────────────────────────────────────────────────
-- Declara una variable "n" (NUMBER) leída por teclado.
-- Declara una variable "factorial" inicializada a 1.
-- Usa un bucle FOR (de 1 a n) para calcular n! = n * (n-1) * ... * 1
-- Imprime: "El factorial de X es: Y"
-- (Ejemplo: 5! = 120)
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.6 — Suma acumulativa con LOOP (parada condicional)
-- ────────────────────────────────────────────────────────────
-- Declara variable "i" inicializada a 1 y "suma" inicializada a 0.
-- Usa un bucle LOOP que:
--   - Acumule i en suma
--   - Incremente i en 1
--   - Salga cuando suma > 10 (EXIT WHEN)
-- Imprime: "La suma es: X" (resultado esperado: 15)
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.7 — Tabla de multiplicar
-- ────────────────────────────────────────────────────────────
-- Declara una variable "n" (NUMBER) leída por teclado.
-- Usa un bucle FOR (de 1 a 10) para imprimir la tabla de multiplicar.
-- Formato: "X x 1 = X", "X x 2 = X", etc.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.8 — Contar dígitos de un número
-- ────────────────────────────────────────────────────────────
-- Declara una variable "num" (NUMBER) leída por teclado (positiva).
-- Declara una variable "digitos" inicializada a 0.
-- Usa un bucle WHILE: mientras num > 0, divide entre 10 y cuenta.
-- Imprime: "El número X tiene Y dígitos"
-- (Ejemplo: 12345 tiene 5 dígitos)
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.9 — Serie de Fibonacci
-- ────────────────────────────────────────────────────────────
-- Declara variables: a=0, b=1, c (para calcular la siguiente).
-- Genera e imprime los primeros 10 números de Fibonacci.
-- Fórmula: c = a + b; luego a = b, b = c
-- Imprime todos separados por espacio o coma.
-- Serie: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.10 — Números primos
-- ────────────────────────────────────────────────────────────
-- Declara una variable "n" (NUMBER) leída por teclado.
-- Declara una variable booleana "es_primo" inicializada a TRUE.
-- Un número es primo si no es divisible por ningún número
-- desde 2 hasta la raíz cuadrada de n.
-- Imprime: "X es primo" o "X no es primo"
-- Pista: usa MOD(num, i) = 0 para comprobar divisibilidad.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.11 — Pirámide de números
-- ────────────────────────────────────────────────────────────
-- Declara una variable "n" (NUMBER) leída por teclado.
-- Imprime una pirámide creciente:
--   1
--   1 2
--   1 2 3
--   ...
--   1 2 3 ... n
-- Usa un bucle anidado FOR.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 2.12 — Suma de números pares e impares
-- ────────────────────────────────────────────────────────────
-- Declara variables: "suma_pares" y "suma_impares" inicializadas a 0.
-- Recorre los números del 1 al 100 con un bucle FOR.
-- Si el número es par (MOD(i,2)=0), súmalos a suma_pares.
-- Si es impar, súmalos a suma_impares.
-- Imprime ambos totales.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────