-- ============================================================
-- 📝 BLOQUE 3 — Interacción con la BD: SELECT INTO, %TYPE, %ROWTYPE
-- ============================================================
-- Lee la teoría en: teoria/T03_select_into.md
-- Valida tus soluciones con: tests/T03_select_into.sql
-- ============================================================

SET SERVEROUTPUT ON;

-- ────────────────────────────────────────────────────────────
-- Ejercicio 3.1 — Suma aleatoria con DBMS_RANDOM
-- ────────────────────────────────────────────────────────────
-- Declara variables para:
--   - n: número de iteraciones (genera con TRUNC(DBMS_RANDOM.VALUE(1, 11)))
--   - aleatorio: para almacenar cada número aleatorio
--   - suma: inicializada a 0
-- Imprime el número de iteraciones.
-- Usa un bucle FOR de 1 a n:
--   - Genera un aleatorio con TRUNC(DBMS_RANDOM.VALUE(10, 101))
--   - Imprime "Número i: X" y acumúlalo en suma
-- Imprime "Suma total: X"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 3.2 — Múltiplos de 3 entre 1 y 100
-- ────────────────────────────────────────────────────────────
-- Declara una variable "contador" inicializada a 0.
-- Usa un bucle FOR de 1 a 100.
-- Si MOD(i, 3) = 0, incrementa el contador.
-- Imprime: "Múltiplos de 3 entre 1 y 100: 33"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 3.3 — Día de la semana actual
-- ────────────────────────────────────────────────────────────
-- Declara:
--   - nombre_dia (VARCHAR2(20))
--   - num_dia (NUMBER)
-- Asigna a nombre_dia usando: TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE=SPANISH')
-- Asigna a num_dia usando: TO_NUMBER(TO_CHAR(SYSDATE, 'D'))
-- Imprime: "Día: X, número: Y" (usa TRIM en nombre_dia)
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 3.4 — COUNT de departamentos
-- ────────────────────────────────────────────────────────────
-- Declara una variable "total" (NUMBER).
-- Usa SELECT COUNT(*) INTO para contar las filas de la tabla SEDES.
-- Imprime: "Número de departamentos: X"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 3.5 — Suma de unidades por producto
-- ────────────────────────────────────────────────────────────
-- PARTE A: Declara una variable "total" (NUMBER).
-- Suma las unidades del producto 20 con:
--   SELECT SUM(unidades) INTO total FROM ventas WHERE productonu = 20
-- Imprime: "Total unidades producto 20: X"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- PARTE B: Declara "total" (NUMBER) y "numpro" (NUMBER, teclado).
-- Suma las unidades del producto indicado por teclado.
-- Imprime: "Total unidades producto X: Y"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 3.6 — SELECT INTO con %TYPE
-- ────────────────────────────────────────────────────────────
-- Declara:
--   - vnombre usando: sedes.nombre%TYPE
--   - vlocalidad usando: sedes.localidad%TYPE
-- Obtén el nombre y localidad del departamento 20.
-- Imprime: "Nombre: X, Localidad: Y"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 3.7 — Uso de %TYPE para suma de unidades
-- ────────────────────────────────────────────────────────────
-- Declara "total_unidades" usando: ventas.unidades%TYPE
-- Suma TODAS las unidades de la tabla ventas.
-- Imprime: "Total unidades en ventas: X"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 3.8 — Uso de %ROWTYPE
-- ────────────────────────────────────────────────────────────
-- Declara "fila_dep" usando: sedes%ROWTYPE
-- Carga la fila completa del departamento 40 con SELECT * INTO.
-- Imprime: "Departamento: X, Localidad: Y"
-- (accede con fila_dep.nombre y fila_dep.localidad)
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 3.9 — AVG de precios con %TYPE
-- ────────────────────────────────────────────────────────────
-- Declara "precio_medio" usando: items.precio%TYPE
-- Calcula el precio medio de todos los productos.
-- Imprime: "Precio medio: X"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 3.10 — %ROWTYPE para un cliente
-- ────────────────────────────────────────────────────────────
-- Declara "cliente" usando: clientes%ROWTYPE
-- Carga los datos del cliente con clientenu = 101.
-- Imprime su nombre y ciudad.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 3.11 — Múltiples consultas en un bloque
-- ────────────────────────────────────────────────────────────
-- Declara 4 variables para almacenar:
--   - num_productos: COUNT(*) de items
--   - total_unidades: SUM(unidades) de ventas
--   - precio_max: MAX(precio) de items
--   - precio_min: MIN(precio) de items
-- Ejecuta las 4 consultas en el mismo bloque.
-- Imprime los 4 resultados.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────