-- ============================================================
-- 📝 BLOQUE 5 — Tipos Compuestos: Arrays (VARRAY)
-- ============================================================
-- Lee la teoría en: teoria/T05_varray.md
-- Valida tus soluciones con: tests/T05_varray.sql
-- ============================================================

SET SERVEROUTPUT ON;

-- ────────────────────────────────────────────────────────────
-- Ejercicio 5.1 — VARRAY de cadenas con métodos básicos
-- ────────────────────────────────────────────────────────────
-- Declara un TYPE "tacad" IS VARRAY(4) OF VARCHAR2(30).
-- Declara "vtacad" inicializado con: tacad('Hola', 'Mundo', 'PL/SQL')
--
-- Imprime:
--   - vtacad.FIRST
--   - vtacad.COUNT
--   - vtacad.LAST
--   - vtacad.LIMIT
--   - El elemento en posición 3: vtacad(3)
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 5.2 — VARRAY de registros TPERSONA
-- ────────────────────────────────────────────────────────────
-- Declara TYPE "tpersona" IS RECORD con: edad (NUMBER), nombre (VARCHAR2(30))
-- Declara TYPE "tapersona" IS VARRAY(3) OF tpersona
-- Declara "vtapersona" inicializado vacío: tapersona()
-- Declara variables para edad y nombre (teclado) del tercer elemento.
--
-- Haz EXTEND(3) para reservar 3 posiciones.
-- Asigna a vtapersona(1): edad=1, nombre='ANA'
-- Asigna a vtapersona(2): edad=2, nombre='ANDRES'
-- Asigna a vtapersona(3): los valores leídos por teclado.
--
-- Recorre con FOR desde FIRST hasta LAST e imprime cada nombre.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 5.3 — VARRAY numérico rellenado con bucle
-- ────────────────────────────────────────────────────────────
-- Declara TYPE "tavnum" IS VARRAY(4) OF NUMBER
-- Declara "vtavnum" inicializado con 4 ceros: tavnum(0, 0, 0, 0)
--
-- Usa un bucle FOR de 1 a 4 para asignar vtavnum(i) := i * 3
--
-- Imprime: FIRST, COUNT, LAST, LIMIT, vtavnum(3)
-- Imprime "--- Contenido completo ---"
-- Recorre el VARRAY con un segundo FOR e imprime cada posición y su valor.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 5.4 — VARRAY de VARCHAR2 para almacenar ciudades
-- ────────────────────────────────────────────────────────────
-- Declara TYPE "tciudades" IS VARRAY(5) OF VARCHAR2(30)
-- Declara "ciudades" inicializado vacío.
--
-- Pide 5 ciudades por teclado (usa &ciudad1, &ciudad2, etc.)
-- o almacénalas con EXTEND y asignación directa.
-- Imprime todas las ciudades.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 5.5 — VARRAY con TRIM y DELETE
-- ────────────────────────────────────────────────────────────
-- Declara TYPE "tnums" IS VARRAY(5) OF NUMBER
-- Declara "nums" inicializado: tnums(1, 2, 3, 4, 5)
--
-- Imprime "COUNT inicial: " || nums.COUNT
-- Haz TRIM(2) para eliminar los últimos 2 elementos.
-- Imprime "COUNT tras TRIM(2): " || nums.COUNT
-- Imprime el contenido actual del VARRAY.
-- Haz DELETE para vaciarlo completamente.
-- Imprime "COUNT tras DELETE: " || nums.COUNT
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 5.6 — VARRAY de registros para productos
-- ────────────────────────────────────────────────────────────
-- Declara TYPE "tproducto" IS RECORD con:
--   - codigo: items.productonu%TYPE
--   - nombre: items.nombre%TYPE
--   - precio: items.precio%TYPE
-- Declara TYPE "taproductos" IS VARRAY(3) OF tproducto
-- Declara "productos" inicializado vacío.
--
-- Carga los productos 10, 20 y 30 de la tabla items.
-- Usa EXTEND para cada uno y SELECT INTO para cada registro.
-- Imprime los 3 productos.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 5.7 — VARRAY con datos de clientes
-- ────────────────────────────────────────────────────────────
-- Declara TYPE "tcliente" IS RECORD con:
--   - codigo: clientes.clientenu%TYPE
--   - nombre: clientes.nombre%TYPE
-- Declara TYPE "taclientes" IS VARRAY(10) OF tcliente
-- Declara "clientes" inicializado vacío.
--
-- Carga los 3 primeros clientes de la tabla clientes.
-- Imprime cuántos clientes se cargaron.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────