-- ============================================================
-- 📝 BLOQUE 6 — Cursores
-- ============================================================
-- Lee la teoría en: teoria/T06_cursores.md
-- Valida tus soluciones con: tests/T06_cursores.sql
-- ============================================================

SET SERVEROUTPUT ON;

-- ────────────────────────────────────────────────────────────
-- Ejercicio 6.1 — Cursor explícito con WHILE (FORMA 1)
-- ────────────────────────────────────────────────────────────
-- Declara un cursor "c1" que seleccione depnu de la tabla sedes.
-- Declara una variable "vdepnu" del tipo correspondiente: sedes.depnu%TYPE
--
-- Lógica:
--   1. OPEN c1
--   2. FETCH c1 INTO vdepnu (primer fetch para "cebar" el bucle)
--   3. WHILE c1%FOUND LOOP
--        Imprime: 'Departamento: ' || vdepnu
--        FETCH c1 INTO vdepnu
--      END LOOP
--   4. CLOSE c1
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 6.2 — Cursor FOR combinado con VARRAY (FORMA 2)
-- ────────────────────────────────────────────────────────────
-- Declara cursor "c1": SELECT depnu FROM sedes
-- Declara TYPE "tvarray" IS VARRAY(20) OF NUMBER
-- Declara "varray" inicializado vacío: tvarray()
-- Declara variable "idx" inicializada a 0.
--
-- Usa FOR reg IN c1 LOOP:
--   - Incrementa idx
--   - Haz varray.EXTEND
--   - Guarda reg.depnu en varray(idx)
-- END LOOP
--
-- Imprime "--- Contenido del VARRAY ---"
-- Recorre el VARRAY con FOR j IN 1..varray.COUNT e imprime cada elemento.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 6.3 — Cursor con parámetros
-- ────────────────────────────────────────────────────────────
-- Declara cursor "c1(param NUMBER)" que busque el nombre de un producto:
--   SELECT nombre FROM items WHERE productonu = param
-- Declara variable "vnombre" del tipo: items.nombre%TYPE
--
-- El parámetro se lee por teclado: &param
-- Abre con: OPEN c1(&param)
-- Recorre con WHILE %FOUND e imprime el resultado.
-- Cierra el cursor.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 6.4 — REF CURSOR sobre productos (WHILE)
-- ────────────────────────────────────────────────────────────
-- Declara TYPE "ref_cur" IS REF CURSOR
-- Declara variable "c2" de tipo ref_cur
-- Declara "vnombre" del tipo: items.nombre%TYPE
--
-- Primera apertura: OPEN c2 FOR SELECT nombre FROM items
-- Recorre con FETCH y WHILE %FOUND, imprime: 'Producto: ' || vnombre
-- Cierra c2
--
-- Segunda apertura: OPEN c2 FOR SELECT nombre FROM items WHERE productonu IN (20, 40)
-- Recorre e imprime: 'Producto (filtrado): ' || vnombre
-- Cierra c2
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 6.5 — REF CURSOR sobre departamentos (LOOP)
-- ────────────────────────────────────────────────────────────
-- Declara TYPE "ref_cur" IS REF CURSOR
-- Declara variable "c3" de tipo ref_cur
-- Declara "vnombre" del tipo: sedes.nombre%TYPE
--
-- Primera apertura: OPEN c3 FOR SELECT nombre FROM sedes
-- Recorre con LOOP + EXIT WHEN %NOTFOUND, imprime el nombre.
-- Cierra c3
--
-- Segunda apertura: OPEN c3 FOR SELECT nombre FROM sedes WHERE depnu IN (10,20,40)
-- Recorre e imprime los departamentos filtrados.
-- Cierra c3
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 6.6 — Cursor con JOIN (varios campos)
-- ────────────────────────────────────────────────────────────
-- Declara cursor "c_pedidos" que seleccione:
--   - v.pedidonu
--   - c.nombre (nombre del cliente)
--   - v.unidades
-- Desde ventas v JOIN clientes c ON v.clientenu = c.clientenu
--
-- Recorre con FOR reg IN c_pedidos LOOP
-- Imprime: "Pedido X: cliente Y, unidades Z"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 6.7 — Cursor para sumar unidades por producto
-- ────────────────────────────────────────────────────────────
-- Declara cursor "c_productos":
--   SELECT productonu, SUM(unidades) as total
--   FROM ventas GROUP BY productonu
--
-- Recorre con FOR e imprime el total de unidades por producto.
-- Formato: "Producto X: Total unidades = Y"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 6.8 — Cursor con filtro por teclado
-- ────────────────────────────────────────────────────────────
-- Declara variable "busqueda" leída por teclado.
-- Declara cursor "c_sedes(p_localidad VARCHAR2)":
--   SELECT depnu, nombre, localidad FROM sedes
--   WHERE localidad LIKE '%' || p_localidad || '%'
--
-- Abre con OPEN c_sedes(busqueda)
-- Recorre e imprime los departamentos encontrados.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 6.9 — REF CURSOR dinámico
-- ────────────────────────────────────────────────────────────
-- Declara TYPE "ref_cur" IS REF CURSOR
-- Declara variable "c_5" de tipo ref_cur
-- Declara variables para pedidonu y clientenu.
--
-- Abre con OPEN c_5 FOR una consulta que obtenga los 5 primeros pedidos.
-- (Usa ROWNUM o FETCH FIRST 5 ROWS ONLY según tu versión)
-- Recorre con LOOP + EXIT WHEN %NOTFOUND.
-- Imprime cada pedido.
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────

-- ────────────────────────────────────────────────────────────
-- Ejercicio 6.10 — Cursor con ordenación
-- ────────────────────────────────────────────────────────────
-- Declara cursor "c_productos":
--   SELECT nombre, precio FROM items ORDER BY precio DESC
--
-- Recorre con FOR e imprime: "X - Precio: Y"
-- ────────────────────────────────────────────────────────────
-- Escribe tu código aquí
-- ────────────────────────────────────────────────────────────