import java.util.Scanner;

import nivel1_fundamentos_lambda.*;
import nivel2_streams_basicos.*;
import nivel3_method_references.*;
import nivel4_optional.*;
import nivel5_avanzado_collectors.*;
import nivel6_flatmap_reduce.*;
import nivel7_experto.*;
import nivel8_generativos_avanzados.*;
import nivel9_desafios_supremos.*;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int opcion;

        do {
            System.out.println("\n╔═══════════════════════════════════════════════════════════════╗");
            System.out.println("║            STREAMS MASTERCLASS — MENÚ PRINCIPAL               ║");
            System.out.println("╠═══════════════════════════════════════════════════════════════╣");
            System.out.println("║  NIVEL 1: FUNDAMENTOS LAMBDA (1-8)                           ║");
            System.out.println("║   1. Primer contacto Lambda              (con guía)           ║");
            System.out.println("║   2. Lambda sin guía                     (sin guía)           ║");
            System.out.println("║   3. Comparator.comparing                (con guía)           ║");
            System.out.println("║   4. Orden multicriterio                 (sin guía)           ║");
            System.out.println("║   5. Predicate y Consumer                (con guía)           ║");
            System.out.println("║   6. Function y transformación           (sin guía)           ║");
            System.out.println("║   7. Composición de Predicados           (con guía)           ║");
            System.out.println("║   8. Lambda como parámetro               (sin guía)           ║");
            System.out.println("╠═══════════════════════════════════════════════════════════════╣");
            System.out.println("║  NIVEL 2: STREAMS BÁSICOS (9-16)                             ║");
            System.out.println("║   9. Primer Stream (filter+collect)      (con guía)           ║");
            System.out.println("║  10. Filter encadenado                   (sin guía)           ║");
            System.out.println("║  11. Map transformación                  (con guía)           ║");
            System.out.println("║  12. Sorted y Distinct                   (sin guía)           ║");
            System.out.println("║  13. Count y forEach                     (con guía)           ║");
            System.out.println("║  14. MapToInt estadísticas               (sin guía)           ║");
            System.out.println("║  15. Limit, Skip, Peek                   (con guía)           ║");
            System.out.println("║  16. Pipeline completo                   (sin guía)           ║");
            System.out.println("╠═══════════════════════════════════════════════════════════════╣");
            System.out.println("║  NIVEL 3: METHOD REFERENCES + COLLECTORS (17-24)             ║");
            System.out.println("║  17. MR: Clase::metodoInstancia          (con guía)           ║");
            System.out.println("║  18. MR: objeto::met y Clase::static     (sin guía)           ║");
            System.out.println("║  19. Comparator.comparing + MR           (con guía)           ║");
            System.out.println("║  20. Collectors.toMap                    (sin guía)           ║");
            System.out.println("║  21. groupingBy y partitioningBy         (con guía)           ║");
            System.out.println("║  22. joining y counting                  (sin guía)           ║");
            System.out.println("║  23. anyMatch, allMatch, noneMatch       (con guía)           ║");
            System.out.println("║  24. findFirst y findAny                 (sin guía)           ║");
            System.out.println("╠═══════════════════════════════════════════════════════════════╣");
            System.out.println("║  NIVEL 4: OPTIONAL (25-29)                                   ║");
            System.out.println("║  25. Optional creación básica            (con guía)           ║");
            System.out.println("║  26. Optional.map y orElse               (sin guía)           ║");
            System.out.println("║  27. Optional.flatMap                    (con guía)           ║");
            System.out.println("║  28. orElseGet, orElseThrow, ifPresent   (sin guía)           ║");
            System.out.println("║  29. Optional con Streams                (con guía)           ║");
            System.out.println("╠═══════════════════════════════════════════════════════════════╣");
            System.out.println("║  NIVEL 5: COLLECTORS AVANZADOS (30-34)                       ║");
            System.out.println("║  30. groupingBy con downstream           (sin guía)           ║");
            System.out.println("║  31. toMap con merge function            (con guía)           ║");
            System.out.println("║  32. toSet y toCollection(TreeSet)       (sin guía)           ║");
            System.out.println("║  33. Productos con Streams               (con guía)           ║");
            System.out.println("║  34. Productos sin guía                  (sin guía)           ║");
            System.out.println("╠═══════════════════════════════════════════════════════════════╣");
            System.out.println("║  NIVEL 6: FLATMAP, REDUCE, FUENTES (35-42)                  ║");
            System.out.println("║  35. flatMap introducción                (con guía)           ║");
            System.out.println("║  36. flatMap con Pedidos                 (sin guía)           ║");
            System.out.println("║  37. reduce básico                       (con guía)           ║");
            System.out.println("║  38. reduce avanzado con Pedidos         (sin guía)           ║");
            System.out.println("║  39. flatMap con Strings                 (con guía)           ║");
            System.out.println("║  40. flatMap+reduce+groupingBy           (sin guía)           ║");
            System.out.println("║  41. Streams sobre Maps                  (con guía)           ║");
            System.out.println("║  42. Streams desde Arrays/IntStream      (sin guía)           ║");
            System.out.println("╠═══════════════════════════════════════════════════════════════╣");
            System.out.println("║  NIVEL 7: RETOS EXPERTO (43-50) — SIN PISTAS                ║");
            System.out.println("║  43. Informe completo RRHH                                   ║");
            System.out.println("║  44. Informe de ventas (Pedidos)                              ║");
            System.out.println("║  45. Top-N por categoría                                      ║");
            System.out.println("║  46. Transformación completa                                  ║");
            System.out.println("║  47. reduce como Collector manual                             ║");
            System.out.println("║  48. Pipeline multi-modelo                                    ║");
            System.out.println("║  49. Optional avanzado cadenas                                ║");
            System.out.println("║  50. DESAFÍO FINAL nivel 7                                    ║");
            System.out.println("╠═══════════════════════════════════════════════════════════════╣");
            System.out.println("║  NIVEL 8: GENERATIVOS Y COLLECTORS AVANZADOS (51-57)        ║");
            System.out.println("║  51. Stream.generate e iterate           (con guía)           ║");
            System.out.println("║  52. Iterate: Fibonacci y secuencias     (sin guía)           ║");
            System.out.println("║  53. Downstream Collectors avanzados     (con guía)           ║");
            System.out.println("║  54. Summarizing y estadísticas          (sin guía)           ║");
            System.out.println("║  55. Collector.of personalizado          (con guía)           ║");
            System.out.println("║  56. UnaryOperator y BinaryOperator      (sin guía)           ║");
            System.out.println("║  57. Pipeline multinivel combinado       (sin guía)           ║");
            System.out.println("╠═══════════════════════════════════════════════════════════════╣");
            System.out.println("║  NIVEL 9: DESAFÍOS SUPREMOS (58-65) — SIN PISTAS            ║");
            System.out.println("║  58. Analizador de frecuencia de palabras                     ║");
            System.out.println("║  59. Simulador de consultas SQL                               ║");
            System.out.println("║  60. Motor de reglas con Predicados                           ║");
            System.out.println("║  61. Matrices numéricas con Streams                           ║");
            System.out.println("║  62. Ranking ponderado de empleados                           ║");
            System.out.println("║  63. Reportes multi-modelo cruzados                           ║");
            System.out.println("║  64. ETL Pipeline completo                                    ║");
            System.out.println("║  65. DESAFÍO SUPREMO FINAL                                    ║");
            System.out.println("╠═══════════════════════════════════════════════════════════════╣");
            System.out.println("║   0. SALIR                                                    ║");
            System.out.println("╚═══════════════════════════════════════════════════════════════╝");
            System.out.print("Elige ejercicio (0-65): ");

            opcion = sc.nextInt();
            System.out.println();

            switch (opcion) {
                case 0: System.out.println("¡Hasta pronto!"); break;
                case 1: Ejercicio01_PrimerContactoLambda.demostracion(); Ejercicio01_PrimerContactoLambda.ejercicio(); break;
                case 2: Ejercicio02_LambdaSinGuia.demostracion(); Ejercicio02_LambdaSinGuia.ejercicio(); break;
                case 3: Ejercicio03_ComparatorComparing.demostracion(); Ejercicio03_ComparatorComparing.ejercicio(); break;
                case 4: Ejercicio04_OrdenMulticriterioSinGuia.demostracion(); Ejercicio04_OrdenMulticriterioSinGuia.ejercicio(); break;
                case 5: Ejercicio05_PredicateYConsumer.demostracion(); Ejercicio05_PredicateYConsumer.ejercicio(); break;
                case 6: Ejercicio06_FunctionYTransformacion.demostracion(); Ejercicio06_FunctionYTransformacion.ejercicio(); break;
                case 7: Ejercicio07_ComposicionPredicados.demostracion(); Ejercicio07_ComposicionPredicados.ejercicio(); break;
                case 8: Ejercicio08_LambdaComoParametro.demostracion(); Ejercicio08_LambdaComoParametro.ejercicio(); break;
                case 9: Ejercicio09_PrimerStream.demostracion(); Ejercicio09_PrimerStream.ejercicio(); break;
                case 10: Ejercicio10_FilterEncadenadoSinGuia.demostracion(); Ejercicio10_FilterEncadenadoSinGuia.ejercicio(); break;
                case 11: Ejercicio11_MapTransformacion.demostracion(); Ejercicio11_MapTransformacion.ejercicio(); break;
                case 12: Ejercicio12_SortedYDistinct.demostracion(); Ejercicio12_SortedYDistinct.ejercicio(); break;
                case 13: Ejercicio13_CountYForEach.demostracion(); Ejercicio13_CountYForEach.ejercicio(); break;
                case 14: Ejercicio14_MapToIntEstadisticas.demostracion(); Ejercicio14_MapToIntEstadisticas.ejercicio(); break;
                case 15: Ejercicio15_LimitSkipPeek.demostracion(); Ejercicio15_LimitSkipPeek.ejercicio(); break;
                case 16: Ejercicio16_PipelineCompletoSinGuia.demostracion(); Ejercicio16_PipelineCompletoSinGuia.ejercicio(); break;
                case 17: Ejercicio17_ReferenciaMetodoInstancia.demostracion(); Ejercicio17_ReferenciaMetodoInstancia.ejercicio(); break;
                case 18: Ejercicio18_ReferenciaObjetoYEstatico.demostracion(); Ejercicio18_ReferenciaObjetoYEstatico.ejercicio(); break;
                case 19: Ejercicio19_ComparatorConMR.demostracion(); Ejercicio19_ComparatorConMR.ejercicio(); break;
                case 20: Ejercicio20_CollectToMapSinGuia.demostracion(); Ejercicio20_CollectToMapSinGuia.ejercicio(); break;
                case 21: Ejercicio21_GroupingByConGuia.demostracion(); Ejercicio21_GroupingByConGuia.ejercicio(); break;
                case 22: Ejercicio22_JoiningYCounting.demostracion(); Ejercicio22_JoiningYCounting.ejercicio(); break;
                case 23: Ejercicio23_AnyMatchAllMatchNoneMatch.demostracion(); Ejercicio23_AnyMatchAllMatchNoneMatch.ejercicio(); break;
                case 24: Ejercicio24_FindFirstFindAny.demostracion(); Ejercicio24_FindFirstFindAny.ejercicio(); break;
                case 25: Ejercicio25_OptionalCreacionBasica.demostracion(); Ejercicio25_OptionalCreacionBasica.ejercicio(); break;
                case 26: Ejercicio26_OptionalMapYOrElse.demostracion(); Ejercicio26_OptionalMapYOrElse.ejercicio(); break;
                case 27: Ejercicio27_OptionalFlatMap.demostracion(); Ejercicio27_OptionalFlatMap.ejercicio(); break;
                case 28: Ejercicio28_OptionalOrElseThrow.demostracion(); Ejercicio28_OptionalOrElseThrow.ejercicio(); break;
                case 29: Ejercicio29_OptionalConStreams.demostracion(); Ejercicio29_OptionalConStreams.ejercicio(); break;
                case 30: Ejercicio30_GroupingByAvanzado.demostracion(); Ejercicio30_GroupingByAvanzado.ejercicio(); break;
                case 31: Ejercicio31_ToMapConMerge.demostracion(); Ejercicio31_ToMapConMerge.ejercicio(); break;
                case 32: Ejercicio32_CollectToSetYTreeSet.demostracion(); Ejercicio32_CollectToSetYTreeSet.ejercicio(); break;
                case 33: Ejercicio33_ProductosConStreams.demostracion(); Ejercicio33_ProductosConStreams.ejercicio(); break;
                case 34: Ejercicio34_ProductosSinGuia.demostracion(); Ejercicio34_ProductosSinGuia.ejercicio(); break;
                case 35: Ejercicio35_FlatMapIntroduccion.demostracion(); Ejercicio35_FlatMapIntroduccion.ejercicio(); break;
                case 36: Ejercicio36_FlatMapConPedidos.demostracion(); Ejercicio36_FlatMapConPedidos.ejercicio(); break;
                case 37: Ejercicio37_ReduceBasico.demostracion(); Ejercicio37_ReduceBasico.ejercicio(); break;
                case 38: Ejercicio38_ReduceAvanzadoSinGuia.demostracion(); Ejercicio38_ReduceAvanzadoSinGuia.ejercicio(); break;
                case 39: Ejercicio39_FlatMapYStrings.demostracion(); Ejercicio39_FlatMapYStrings.ejercicio(); break;
                case 40: Ejercicio40_FlatMapReduceCombinado.demostracion(); Ejercicio40_FlatMapReduceCombinado.ejercicio(); break;
                case 41: Ejercicio41_StreamDeMaps.demostracion(); Ejercicio41_StreamDeMaps.ejercicio(); break;
                case 42: Ejercicio42_StreamDeArrays.demostracion(); Ejercicio42_StreamDeArrays.ejercicio(); break;
                case 43: Ejercicio43_InformeEmpleados.demostracion(); Ejercicio43_InformeEmpleados.ejercicio(); break;
                case 44: Ejercicio44_InformePedidos.demostracion(); Ejercicio44_InformePedidos.ejercicio(); break;
                case 45: Ejercicio45_TopNPorCategoria.demostracion(); Ejercicio45_TopNPorCategoria.ejercicio(); break;
                case 46: Ejercicio46_TransformacionCompleta.demostracion(); Ejercicio46_TransformacionCompleta.ejercicio(); break;
                case 47: Ejercicio47_ReduceCustomCollector.demostracion(); Ejercicio47_ReduceCustomCollector.ejercicio(); break;
                case 48: Ejercicio48_PipelineMultiModelo.demostracion(); Ejercicio48_PipelineMultiModelo.ejercicio(); break;
                case 49: Ejercicio49_OptionalAvanzado.demostracion(); Ejercicio49_OptionalAvanzado.ejercicio(); break;
                case 50: Ejercicio50_DesafioFinal.demostracion(); Ejercicio50_DesafioFinal.ejercicio(); break;
                case 51: Ejercicio51_StreamGenerateIterate.demostracion(); Ejercicio51_StreamGenerateIterate.ejercicio(); break;
                case 52: Ejercicio52_IterateFibonacci.demostracion(); Ejercicio52_IterateFibonacci.ejercicio(); break;
                case 53: Ejercicio53_DownstreamCollectors.demostracion(); Ejercicio53_DownstreamCollectors.ejercicio(); break;
                case 54: Ejercicio54_SummarizingEstadisticas.demostracion(); Ejercicio54_SummarizingEstadisticas.ejercicio(); break;
                case 55: Ejercicio55_CollectorOfPersonalizado.demostracion(); Ejercicio55_CollectorOfPersonalizado.ejercicio(); break;
                case 56: Ejercicio56_UnaryBinaryOperator.demostracion(); Ejercicio56_UnaryBinaryOperator.ejercicio(); break;
                case 57: Ejercicio57_PipelineMultinivel.demostracion(); Ejercicio57_PipelineMultinivel.ejercicio(); break;
                case 58: Ejercicio58_AnalizadorFrecuencias.demostracion(); Ejercicio58_AnalizadorFrecuencias.ejercicio(); break;
                case 59: Ejercicio59_SimuladorSQL.demostracion(); Ejercicio59_SimuladorSQL.ejercicio(); break;
                case 60: Ejercicio60_MotorReglas.demostracion(); Ejercicio60_MotorReglas.ejercicio(); break;
                case 61: Ejercicio61_MatricesNumericas.demostracion(); Ejercicio61_MatricesNumericas.ejercicio(); break;
                case 62: Ejercicio62_RankingPonderado.demostracion(); Ejercicio62_RankingPonderado.ejercicio(); break;
                case 63: Ejercicio63_ReportesMultiModelo.demostracion(); Ejercicio63_ReportesMultiModelo.ejercicio(); break;
                case 64: Ejercicio64_ETLPipeline.demostracion(); Ejercicio64_ETLPipeline.ejercicio(); break;
                case 65: Ejercicio65_DesafioSupremo.demostracion(); Ejercicio65_DesafioSupremo.ejercicio(); break;
                default: System.out.println("Opción no válida. Elige entre 0 y 65."); break;
            }
        } while (opcion != 0);

        sc.close();
    }
}
